apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  labels:
    argocd.argoproj.io/instance: ekstop-dev
  name: auth-core-builders
  namespace: argocd
spec:
  generators:
    - list:
        elements:
          - appName: auth-core-builders
            clusterName: ekstop-dev
            clusterUrl: https://kubernetes.default.svc
            environment: dev
            namespace: dev
            project: ekstop-dev
            repositoryUrl: https://github.com/moisescardoso83/argo.git
            targetRevision: HEAD
  syncPolicy:
    preserveResourcesOnDeletion: true
  template:
    metadata:
      name: '{{ appName }}'
      namespace: '{{ namespace }}'
    spec:
      destination:
        namespace: '{{ namespace }}'
        server: '{{ clusterName }}'
      project: '{{ project }}'
      source:
        kustomize:
          namePrefix: '{{ appName }}'
        path: '{{ appName }}/overlays/{{ environment }}'
        repoURL: '{{ repositoryUrl }}'
        targetRevision: '{{ targetRevision }}'
