apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: nginx-applicationset
  namespace: argocd
spec:
  generators:
    - list:
        elements:
          - cluster: ekstop-dev
            environment: dev
    metadata:
      name: nginx-{{environment}}
    spec:
      project: default
      source:
        repoURL: 'https://github.com/moisescardoso83/argo.git'
        targetRevision: main
        path: kustomize/overlays/{{environment}}
      destination:
        server: '{{cluster}}'
        namespace: '{{environment}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
